### ISSUE TITLE
Add Status Bar facility to VSCode extension

### ISSUE THREAD

**Issue by sagerb** [posit-dev/publisher#1020]
This will allow us to display informational messages without requiring the user to respond. 

The first example of use requested is as a response to hitting the refresh button of deployments.

NOTE: VSCode has multiple ways of showing status. While this proposal gives us one way, it is unclear where we need additional helper function (as what was proposed in the PR which was closed without merging) or if we simply need to understand/use the existing VSCode APIs appropriately.

**Comment by dotNomad** [comment]
I believe this is completed, unless `window.withProgress` didn't encompass everything we were thinking with this one? What do you think @sagerb?

**Comment by sagerb** [comment]
I believe it is completed as well. Closing.
