### ISSUE TITLE
Add an endpoint to get the next untitled deployment name

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#1083]

**Comment by dotNomad** [comment]
Closing this one up as state. The most recent work generates a unique name:
- for the Content Records it is `deployment-` with 4 unique characters
- for Configurations it is `trimmed-deployment-name-` with 4 unique characters

This is done without an endpoint, and we just traverse the Content Records and/or Configurations we already have access to in the extension to verify file name uniqueness.
