### ISSUE TITLE
Support quarto-rendered scripts

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#1208]
From @aronatkins: https://positpbc.slack.com/archives/C014UG28GB1/p1711546060484779

> I would like for the publisher to support Quarto projects containing a single rendered script and standalone rendered scripts published as Quarto content. I’ve got Connect Jump Start examples and documentation ready to go, along with rsconnect and rsconnect-python changes which support the content.

> The Connect changes are probably the best resources, along with the Quarto documentation:

>    * https://quarto.org/docs/computations/render-scripts.html
>    * Jump Start and tests: https://github.com/rstudio/connect/pull/26213
>    * Documentation: https://github.com/rstudio/connect/pull/26260

The corresponding rsconnect PR is https://github.com/rstudio/rsconnect/pull/1055.

**Comment by kgartland-rstudio** [comment]
We had a request for this from SE here:
https://positpbc.slack.com/archives/C05D7NZD52S/p1727215522683349

**Comment by sagerb** [comment]
Hopefully, this is just addition of a new content type, and the supporting code for it?
