### ISSUE TITLE
Feedback: hierarchical Files view

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#1210]
https://positpbc.slack.com/archives/C06B0UZKT34/p1711545418302709

> Feedback: The Deployment Files >> Included Files listing offers no hierarchy, which means that using the UI to exclude files is tedious for Quarto projects, which render input.html and lots of files beneath input_files. It’s worse for Quarto websites and other, richer projects, which render everything beneath the some output directory like _site.The good thing is that I can watch the .positignore get built, notice that there are files contained within hierarchical paths, and adjust those rules as they’re added. It’s really nice that the include/exclude lists are automatically updated to reflect those edits.

**Comment by dotNomad** [comment]
Took a look at what this would entail. Currently we send over the included and excluded files as a flat array in `homeView::sendRefreshedFilesList()`. It uses `splitFilesOnInclusion` to do this separation.

The home state in the Vue app displays those arrays pretty simply.

We would need to send over the whole file structure and based on the view type that was selected do this splitting, or constructed a hierarchical files view.
