### ISSUE TITLE
Publisher icon stroke is thicker than normal icons used in VSCode

### ISSUE THREAD

**Issue by sagerb** [posit-dev/publisher#1214]
The lines of the “Deploy” button feels really heavy in the deployment listing, especially when compared to the adjacent “View” button. The difference in line weight is also present in the left-hand-side extension selector, doesn’t feel as obvious, since there is space between the “Posit Publisher” and “Database Connections” icons, for example.

![Image](https://github.com/posit-dev/publisher/assets/17675905/8ac6e578-0e39-4098-8f13-7bcf08c273f8)

For comparison:

![Image](https://github.com/posit-dev/publisher/assets/17675905/a0a01d6e-945b-42f4-ae61-fe5986d4c9da)

**Comment by dotNomad** [comment]
We are now using a new icon, and while the stroke width is a bit larger than the VS Code codicons it fits much better. Going to close this one up as stale, and we can open a new issue if we think we need to make changes to the new icon.
