### ISSUE TITLE
Handle scenario where user has no credentials for a deployment.

### ISSUE THREAD

**Issue by sagerb** [posit-dev/publisher#1280]
This may occur initially or because the user has chosen to refresh credentials

Have to handle:

- deployment section:
    - Disabling / removing deploy operation icon
    - Update of the tooltip
- Home View: 
    - Disable entry within dropdown, with some indication of why it is disabled
    - Update deploy button enabled, if the selected entry becomes disabled
    - Update deployment status to indicate they have no credentials that match the URL

We have talked about adding an API that could be called for each deployment, which indicates if there are any known credentials. This was thought of to remove the responsibility of the UX to loop through existing credentials and see if there are any URL matches. Having to make an API call for each of the deployments would be pretty chatty, so I'm not in favor of this alternative API idea, I'd rather just check within the UX.

One possible alternative is then to make it easier to check, so we could add some type of metadata field to the deployment API which would return if there were any credentials for the deployment, thereby eliminating the need for the UX to query all accounts and then do it's own matching. This would be helpful in the future when the backend would also be making sure there are some credentials which have ownership/collaboration access to the content item on the server, as the metadata could be enhanced.

**Comment by dotNomad** [comment]
Moving this out of `v1.2.0` for now, but I believe we can close this one. Looking at the requirements above I believe they are all taken care of currently
