### ISSUE TITLE
Project Files and Python Packages sections can hide under Credentials section

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#1636]
This seems to keep happening to me but the Project Files and Python Packages often slip under the Credentials section and I can't find them. 

The Credentials and Configuration sections don't have the same problem. I suspect those are "tree views" while Project Files and Python Packages are webview.

https://github.com/posit-dev/publisher/assets/41300090/3d156ee3-ef19-4743-a2f7-5886f3bd1b35

**Comment by dotNomad** [comment]
Closing this one as everything is now inside the webview. Nothing will be hidden under, the entire Home view is scroll-able.
