### ISSUE TITLE
Secrets store

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#1678]
Provide a way to deploy with secrets, since we recommend against putting them in the config file as environment variables.

This needs more discussion. One proposal:
* Provide a client-side secret store, using the OS keychain as we do for credentials. 
* Store key/value pairs and provide a CRUD API.
* Create a UI treeview to allow editing the list of secrets.
* Show warning message with "fix me" link in the UI if any secrets in the config are not present in the local store.
* During preflight, ensure that all secrets called out in the config are present in the local store; err if any are missing.
* At deployment time, inject secret values via Connect's environment variables API.

**Comment by dotNomad** [comment]
This looks to be superseded by #2260 can I close this one up?
