### ISSUE TITLE
R Scan fails when there is no `renv/activate.R`

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#1745]
The Scan button appears when there's no `renv.lock` file. If you have a `renv/activate.R` file in the project, the Scan button creates a renv.lock file for you.

If there is no `renv/activate.R` file, the Scan button will fail with:
> An error has occurred at homeView::_onScanForRPackageRequirements, Code=ERR_BAD_RESPONSE, Msg=Request failed with status code 500, URL=http://localhost:61514/api/post/packages/r/scan

Logs:
> time=2024-05-29T14:03:37.105-04:00 level=DEBUG msg="Running command" cmd="C:\\Program Files (x86)\\R\\R-4.4.0\\bin\\R.exe" args="-s -e renv::snapshot(lockfile=\"c:\\Users\\kgartland\\publisher-client\\bundles\\mpg-shinyApp\\renv.lock\")"
> time=2024-05-29T14:03:37.298-04:00 level=ERROR msg="Error running command" command="C:\\Program Files (x86)\\R\\R-4.4.0\\bin\\R.exe" error="exit status 1"
> Error in file(filename, "r", encoding = encoding) : 
>   cannot open the connection
> Calls: source -> file
> In addition: Warning message:
> In file(filename, "r", encoding = encoding) :
>   cannot open file 'renv/activate.R': No such file or directory
> Execution halted
> time=2024-05-29T14:03:37.298-04:00 level=DEBUG msg=renv::snapshot() out="" err="Error in file(filename, \"r\", encoding = encoding) : \r\n  cannot open the connection\r\nCalls: source -> file\r\nIn addition: Warning message:\r\nIn file(filename, \"r\", encoding = encoding) :\r\n  cannot open file 'renv/activate.R': No such file or directory\r\nExecution halted\r\n"
> time=2024-05-29T14:03:37.298-04:00 level=ERROR msg="Internal Server Error" method=POST url=/api/packages/r/scan error="exit status 1"
> time=2024-05-29T14:03:37.298-04:00 level=INFO msg="Access Log" method=POST url=/api/packages/r/scan elapsed_ms=326 status=500 req_size=24 resp_size=21 client_addr=127.0.0.1:61559 req.saveName=renv.lock
> 

If the `Scan` function requires a `renv/activate.R` file, can we hide the Scan button and ask that they run `renv::init()` or  `renv::snapshot()`?  

Additionally, f you _do_ have an renv.lock file but no `renv/activate.R`, and click the eye icon to rewrite the file, it will fail in the same way.

**Comment by dotNomad** [comment]
We currently do not have a scan operation for R packages so we can close this up.
