### ISSUE TITLE
Credential persistence for Workbench

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#1831]
Libraries needed for keyring support aren't always available in Workbench. #1824 introduces a temporary workaround that allows keys to persist for during your workbench session, so we can test. We need a solution to let them persist beyond the workbench session.

**Comment by mmarchetti** [comment]
For 1.1.5, we will go with the implementation in #2063.

**Comment by mmarchetti** [comment]
Updated to use a file-based temporary solution in #2089.

**Comment by dotNomad** [comment]
Verified that this behaves as expected on Workbench, and the keychain is still used on my machine.
