### ISSUE TITLE
Add entrypoint filtering to and Deployment, Configuration, and Inspect APIs

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#1847]
To allow the flow we want for selecting and deploying from a button on entrypoint files we need some APIs to support filtering by entrypoint.

The API endpoints are:
- `api/inspect`
- `api/deployments`
- `api/configurations`

The design is currently to use an optional query parameter to modify the default behavior. `?entrypoint=path` can be passed with the `path` being a relative path to a specific endpoint file.

The response will contain only resources related to that entrypoint.

In the case of the:
- inspect API only potential Configurations with that entrypoint will be returned
- Deployments only Deployments with Configurations using that entrypoint will be returned
- Configurations using that entrypoint will be returned

---

Part of the #1846 epic.

**Comment by mmarchetti** [comment]
See the note in https://github.com/posit-dev/publisher/pull/1916#discussion_r1661579320. The entrypoint matching test will need to be more complex since the `entrypoint` parameter will be relative to the workspace root, and might be a path into a subdirectory.
