### ISSUE TITLE
Support recursive API requests

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#1850]
To support features in the VSCode extension we need a few APIs to support listing all resources, not just the ones in the "workspace root".

To accomplish this the proposal is to have a `?recursive=boolean` optional query param which defaults to `false`. When `true` the endpoint will response with all of the resources found in the root and nested folders.

The APIs that need to support the `recursive` query param:
- `GET /api/deployments`
- `POST /api/inspect`

The `recursive` query param should fail when used in tandem with the `entrypoint` query param mentioned in #1847.

---

Part of the #1849 epic

**Comment by mmarchetti** [comment]
Implemented in #1925, #1928, and #1929.
