### ISSUE TITLE
Support specifying a path for API requests

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#1851]
Several APIs need to be able to specify a `path` to support nested folder deploying flows in the VSCode extension.

The proposed solution is to have:
- an optional query param `?dir=path`
- pass an optional path in the body of the request for applicable responses

The APIs that need adjustments:
- `GET /api/configurations`
- All `/api/configurations/$name` API endpoints since non-root named Configurations will need a path alongside to be identified
- ALL `/api/packages` API endpoints since configurations or file creation needs to know the non-root directory
- `POST and DEL /api/deployments/$name` API endpoints need a path for non-root deployments and configurations

**Note**

The `entrypoint` query parameter mentioned in #1847 will not work alongside the `dir` query param.

---

Part of the #1849 epic

**Comment by dotNomad** [comment]
@mmarchetti I'm taking a look and I'm not seeing support for `dir` in the `/api/packages/python/scan` or `/api/packages/r/scan` endpoints. Am I missing it?

**Comment by mmarchetti** [comment]
> Am I missing it?

Nope, I missed it. See https://github.com/posit-dev/publisher/pull/1919
