### ISSUE TITLE
Add a cancellation API endpoint for publishing

### ISSUE THREAD

**Issue by tdstein** [posit-dev/publisher#195]
Discovery is needed to determine how we will accomplish this.

We know we will need to add a unique identifier to the original publish request to track the process.

We need to modify the events to provide information regarding the identifier for the publish event.

**Comment by jonkeane** [comment]
I'm closing this as not planned, we have other issues like #305 that are similar. And more work is needed outside of publisher to facilitate this regardless (e.g. in Connect)
