### ISSUE TITLE
Files API returns a 500 if the config isn't valid

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#1972]
If you have a config that isn't valid (for example, inspect the repo root which doesn't have a valid entrypoint), the Files API will return a 500. The frontend doesn't call this API unless it has a valid configuration, so this is a cleanup. We'd like it to return a 400 in this case.

**Comment by jonkeane** [comment]
Is this still an issue?

**Comment by dotNomad** [comment]
This is no longer an issue thanks to the work fixing #2157.

Confirmed that calling `GET api/configurations/fastapi-simple-TJ6U/files` returns a `400` with a JSON body like:

```
{
    "code": "invalidTOML",
    "details": {
        "column": 2,
        "filename": "/Users/jordan/development/publishing-client/test/sample-content/fastapi-simple/.posit/publish/fastapi-simple-TJ6U.toml",
        "line": 4
    }
}
```

This occurs when the config has invalid TOML or an unknown key.
https://github.com/posit-dev/publisher/blob/358ce93e0db998a7d5c0e172d5da6e63221d0535/internal/services/api/get_config_files.go#L37
