### ISSUE TITLE
Cannot Add Connect behind Proxy 

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#1974]
We got this from slack:

https://positpbc.slack.com/archives/C05K993PVEV/p1721156669455599

It appears when Connect is behind a proxy we cannot add the server.  

When you add the `palm` url (https://pub.palm.ptd.posit.it/) the following error is thrown:

![Screenshot 2024-07-16 at 3 34 34 PM](https://github.com/user-attachments/assets/5574e944-3f84-436f-bebc-f138755e478c)

Based on the logs, it looks like we're having trouble parsing the response:

> time=2024-07-16T15:11:34.781-04:00 level=INFO msg="Testing authentication" method="Connect API key" url=https://pub.palm.ptd.posit.it/connect/
> time=2024-07-16T15:11:35.654-04:00 level=DEBUG msg="API request" method=GET path=/__api__/v1/user body="" response="<!DOCTYPE html>\n\n\n\n\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n\n    <script type=\"text/javascript\" nonce=\"32Zh1d1fB6Icnylb6KyWqA\">if (typeof module === 'object') {window.module = module; module = undefined;}</script><style type=\"text/css\" nonce=\"32Zh1d1fB6Icnylb6KyWqA\">\n 
> ...
> 

When we _can_ successfully add a Server we hit (dogfood for reference):

> time=2024-07-16T15:18:37.180-04:00 level=INFO msg="Testing authentication" method="Connect API key" url=https://rsc.radixu.com
> time=2024-07-16T15:18:39.521-04:00 level=DEBUG msg="API request" method=GET path=/__api__/v1/user body="" response="" error="unexpected response from the server (401)"
> time=2024-07-16T15:18:39.521-04:00 level=INFO msg="Connect server connectivity check failed" url=https://rsc.radixu.com
> time=2024-07-16T15:18:39.521-04:00 level=INFO msg="Access Log" method=POST url=/api/test-credentials elapsed_ms=2340 status=200 req_size=32 resp_size=27 client_addr=127.0.0.1:64776 req.url=https://rsc.radixu.com

I think we expect a 401 response and we're surprised to hit the proxy.

This URL works with both RStudio IDE (`rsconnect`) and `rsconnect-python`

From @colearendt 

> We let certain things through (from history): X-Auth-Token header is present (for IDE access), or Authorization: Key * header for API requests.
> https://github.com/rstudio/ptd/blob/e72d358f58120144db25cf3cf8aa50690a8bd50a/ptd/src/ptd/pulumi_resources/traefik_forward_auth.py#L153-L154
> Relevant Connect docs:
> https://docs.posit.co/connect/admin/authentication/proxied/#ide-deployment

**Comment by dotNomad** [comment]
There is some kind of validation in the IDE - we could potentially look to see how the IDE validates to catch the same edge cases here. The error message isn't great, but we can look at the implementation:

![Image](https://github.com/user-attachments/assets/17eb974f-2ad2-4220-aea5-c34428196f64)

**Comment by mmarchetti** [comment]
Also remove trailing `connect/` if present.
