### ISSUE TITLE
Clicking Add Configuration doesn't prompt the Progress bar

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#1981]
When you click the `+` to add a Configuration, the Progress bar doesn't display so it doesn't look like anything is loading. This likely has always existed but it's more evident now since we have to scan the entire directory tree for projects.

https://github.com/user-attachments/assets/50b6f3f9-922b-46da-b7b1-22921388dd2a

**Comment by dotNomad** [comment]
Using the latest code off `main` and restarting VSCode and was unable to reproduce this.
