### ISSUE TITLE
mutli-type default title wrong for fastapi

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#1990]
When deploying the `fast-api` example in the [multi-type directory](https://github.com/posit-dev/publisher/tree/main/test/sample-content/multi-type), the Title is set to `multi-type` by default.  However, when deploying the `quarto-proj-none` example in the `multi-type` directory, the Title is set to `quarto-proj-none` as expected.

Small issue, but I'm not sure if there other implications. The configuration file does find the proper `entrypoint` and `type` so it may just be the title that's not being created as expected.

https://github.com/user-attachments/assets/f01062cc-c52c-4d61-b1ad-e2857eeee685

**Comment by mmarchetti** [comment]
I think that's been the behavior for a while. We try to get a title from `quarto inspect`, and fall back to the project directory name if we don't have any other source.

**Comment by kgartland-rstudio** [comment]
ah so quarto works that way because we can run the `quarto inspect` command. I'll close this one.
