### ISSUE TITLE
Disable EvenEasierDeploy component when selection or multi-step is actively collecting input.

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#1995]
![Image](https://github.com/user-attachments/assets/8b09ed57-d56e-4888-a12f-216b4ff98e2f)

I'm thinking we could either update the selector button to say selection in progress and disable the publish button, or something.

**Comment by dotNomad** [comment]
I think making changes to the sidebar while the input is up could cause some pretty distracting flashing back and forth. Movement in the sidebar would distract me away from the input rather than to it.

In the case where the input is dismissed this would cause the selection to jump from a selection, to "Selection in Progress", back to the selection.

**Comment by mmarchetti** [comment]
Let's put this on hold until we get some input from user testing.

**Comment by dotNomad** [comment]
Received more feedback in #2016 so unmarking this as hold.
