### ISSUE TITLE
Credentials: URL Validation

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#2001]
Adding `https://rsc.radixu.com/adsdfafasdf` passes URL validation when it shouldn't.

Adding `https://rsc.radixu.com/connect` passes URL validation but fails API Key validation with...
<img width="617" alt="Screenshot 2024-07-19 at 11 47 12 AM" src="https://github.com/user-attachments/assets/44cfeed3-f5cd-4ba6-badf-3338b7c08ae0">

 If we're supporting the `/connect` path, this should pass.  If we aren't supporting the `/connect` path, I would expect this to fail at the URL validation step with an explanation that `/connect` shouldn't be included in the server url.

**Comment by mmarchetti** [comment]
The API should try the URL as given, and if it fails, try stripping off the /connect suffix. it will need to return the canonical URL to the extension so that the "fixed" URL is the one that gets saved.

**Comment by dotNomad** [comment]
Moving this to triage again to re-discuss since it has been hit in user testing a few times.

**Comment by dotNomad** [comment]
There is a potential half-way point here to just remove everything that isn't the base URL.

Configurations on Connect may or may not have `/connect` and they can set their own paths.

If a customer is using a proxy to point to the Connect Server then using only the base URL could cause an issue.

**Comment by dotNomad** [comment]
We can try stripping things with the API key validation that we do.
