### ISSUE TITLE
Workbench workspaceRoot scanning didn't work correctly

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#2011]
I'm working on reproducing this, but putting this here while I do.

Essentially the `app.py` file wasn't being found when inspecting entrypoints, and only a python file in the `src` directory was being discovered. In VSCode this worked with no issue at all.

**Comment by mmarchetti** [comment]
Try to repro with the Shiny app in https://github.com/posit-dev/posit-conf-survey.
