### ISSUE TITLE
When deploying via Entrypoint Selector a previous deployment can load in the Home View

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#2016]
This just may be me but I thought I'd file it for discussion.  If you're deploying multiple items in the same session using the Entrypoint Selector, it can be confusing what's actually getting deployed.  

Here I have previously deployed a project called `rmd-static-1` successfully.  Now I'm trying to deploy a project called `fastapi-simple`, however the Home View still displays `rmd-static-1` while I'm trying to deploy `fastapi-simple`:

![Screenshot 2024-07-24 at 10 41 55 AM](https://github.com/user-attachments/assets/636fcc3b-e6a9-4571-9e02-5cc8aef590e6)

I wonder if we can change the Home View to switch the `fastapi-simple` project when I click on the entrypoint selector.  It does eventually flip to `fastapi-simple` but that occurs after I kick off the deployment.

**Comment by sagerb** [comment]
I believe this is another solution similar to #1995 , which indicates the same confusion.
