### ISSUE TITLE
Ensure we are scanning Python packages correctly with `uv`

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#2021]
https://github.com/astral-sh/uv

Ensure that the library paths are the same as what they are with `pip`. The package manager setting in the config would still be `pip`, but the extension should find the dependencies and their version (when applicable)

**Comment by mmarchetti** [comment]
Verified.

```
uv venv
source .venv/bin/activate
uv pip install -r requirements.txt
mv requirements.txt requirements.txt.orig
```

In VSCode, ran `Python: Select Interpreter` and chose the workspace .venv, then scanned for requirements. The package versions for installed packages were detected.
