### ISSUE TITLE
Ability to cancel Adding Deployment

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#2027]
Now that we can Add Deployments from larger directories, I'm finding myself wanting to cancel if it's taking too long or if I've triggered it from the wrong directory. I think customers will likely want that as well.

Can we add a cancel button somewhere?

**Comment by mmarchetti** [comment]
I've already hit this twice this morning. My workaround is to restart VSCode or use Reload Window.

**Comment by jonkeane** [comment]
I've also added the feedback label. We didn't get asked for this _directly_ in our interviews, but everyone (except Julia working with R) ran into a long-running deployment that felt awkward and we have to work around it. Some of that is due to Python environment restore times that are outside of our immediate control, but knowing that's a possibility giving someone a cancel when they hit it would be fantastic.

**Comment by dotNomad** [comment]
> Can we add a cancel button somewhere?

I'm curious where you are expecting the cancel button

**Comment by kgartland-rstudio** [comment]
Not sure if you can conditionally add/remove icons in the Deployment heading next to the `+`, but that's where I'd imagine it being:
![Screenshot 2024-07-25 at 1 12 59 PM](https://github.com/user-attachments/assets/a23a9849-7fd8-42eb-aded-a77062b44830)

**Comment by dotNomad** [comment]
> Not sure if you can conditionally add/remove icons in the Deployment heading next to the `+`

We definitely can.

I would prefer to work through making our extension work well when in a large directory and not build work arounds in the interim.

**Comment by kgartland-rstudio** [comment]
> I would prefer to work through making our extension work well when in a large directory and not build work arounds in the interim.

Agree that's a better solution

**Comment by jonkeane** [comment]
> I've also added the feedback label. We didn't get asked for this directly in our interviews, but everyone (except Julia working with R) ran into a long-running deployment that felt awkward and we have to work around it. Some of that is due to Python environment restore times that are outside of our immediate control, but knowing that's a possibility giving someone a cancel when they hit it would be fantastic.

Ooops sorry I misread this at first. My comment here was about the actual deployment not just adding a new one. I think it's still valid (though not about this issue!)

> I would prefer to work through making our extension work well when in a large directory and not build work arounds in the interim.

Agreed, we should get this interface to be speeds where no one would ever have a desire to cancel (cause they don't perceive that it's happening)

**Comment by dotNomad** [comment]
Since we have a handful of people saying we should improve speeds I'll close out as not planned as we work on #1970
