### ISSUE TITLE
Permissions: when opening a folder that includes files/folders without user perms a confusing error is thrown

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#2032]
I hit this originally in Workbench, where this may occur more frequently than a local install but I was able to reproduce locally as well.

Using the Workbench instance here:
https://dev.palm.ptd.posit.it/

If I open the `/home/` directory which includes all Users. I can click Add Deployment but then this error is thrown:

> Unable to continue with project inspection failure. An error has occurred at newDeployment, configurations.inspect, Msg=Cannot read properties of null (reading 'forEach')

![Screenshot 2024-07-25 at 1 52 21 PM](https://github.com/user-attachments/assets/0306c038-dbcb-413c-931c-53ffe6c1acf1)

I was able to reproduce this locally by opening `/` (root) dir and clicking Add Deployment.

**Comment by kgartland-rstudio** [comment]
@mmarchetti : you're right, this also happens on empty folders

**Comment by mmarchetti** [comment]
This is an API bug; curl output is a literal `null`.

**Comment by dotNomad** [comment]
We now get a proper error when we detect no entrypoints due to permissions or empty folders.
