### ISSUE TITLE
Remove any unneeded recursive queries at initialization

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#2049]
With the removal of the Deployments and Configurations view, we don't believe we need any of this information at the very start.

All of our interactions fetch things themselves.

**Comment by sagerb** [comment]
Ignoring the query for credentials, which is extremely lightweight, the original recursive queries for all deployments and all configurations occurred upon the Home View initialization.

With the changes introduced in PRs: #2092 and #2101, the behavior has been improved:
1. If the workspace/folder opened within VSCode has a prior publishing deployment selected, then the recursive queries are eliminated and the only quick queries request a specific deployment and configuration.
2. If there has not yet been a selection made within the publisher, then we must do a scan to determine if we should show the Create Deployment state ("Let's Get Deploying") or the Select deployment action, we perform two more deployment/configuration recursive queries, to accurately populate the selection list.

Issue #2101 (currently in triage) addresses the recursive deployment needed for the second case above, by modifying the UX.

**Comment by sagerb** [comment]
Intention of Issue fixed by linked PRs. Closing.
