### ISSUE TITLE
Update entrypoint selection within `src/multiStepInputs/selectNewOrExistingConfig.ts`

### ISSUE THREAD

**Issue by sagerb** [posit-dev/publisher#2052]
Match implementation from PR: https://github.com/posit-dev/publisher/pull/2051

**Comment by jonkeane** [comment]
Are there other aspects of the implementation on top of making the extensions not-case sensitive? It might be nice to list the changes here too

**Comment by sagerb** [comment]
Entrypoint selection will be modified in #2237  and same implementation should be done here. That will show entrypoints to be open files plus browse button.

**Comment by sagerb** [comment]
From team discussion on 9/24: Not going to implement. The current implementation works optimally for replacing a config for a given deployment, and does not share many of the original concerns of deep recursive inspections (since the new entrypoint needs to be below the associated deployment's project dir). 

If we were to change to the select from all open files (filtered to the same content type) and then allow open folder, we’d have to restrict them to selection of a file within the workspace and one of the same content type or unknown, then force it to be overridden. This would make it harder for the user to understand what is going on. 

For now, just keep it as is. Closing the issue as not planned.
