### ISSUE TITLE
Feedback: automatically exclude contents of `.gitignore` files from deployment

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#2056]
from: https://positpbc.slack.com/archives/C06B0UZKT34/p1722397072282259

Another feedback item, I think the publisher should automatically exclude files and directories that are in my .gitignore. By accident I included a .cache directory in my deployment that had a lot of data in it!

------------

This is an interesting one, as initial feedback from others identified the opposite need (to not have the files git ignored excluded from the deployment).

**Comment by dotNomad** [comment]
I could see users wanting both - only publishing built things not in tracked by the repo, or only wanting to publish necessary files and not files listed in the gitignore.

I'm unsure if we can do this without harming one flow or the other.

**Comment by dotNomad** [comment]
This could be a sign that our auto-include of every file with `*` is too large as a start.

Some other options:
- Have users select the files they want
  - Would be another step in creation
- Include known files
  - Would have to scan for imports to include required modules, or files like CSVs
- A configuration option to list ignore files (like gitignores)
  - Much more complicated

We have to remember that the entrypoint button deploys _right away_ so if we don't prompt the user they will create a deployment right away with the files we select - without prompt.

**Comment by SamEdwardes** [comment]
I have a few thoughts:

- My initial reaction is I think excluding the contents from .gitignore is a reasonable default.
  - .gitignore is often used to exclude secretes from being published to get (e.g. `.env`) files. We also don't want users publishing secretes to Connect or Connect cloud.
  - .gitignore is often used to exclude data. For example temporary artifacts that are generated as part of as script, like in my use case a cache.
- I think the default of '*' is too aggressive, and not what most users would want.
- If .gitignore is too aggressive, here are some ideas for more conservative defaults.

```bash
files = ['*.py', '*.ipynb', '*.qmd', '*.R', '*.Rmd', 'requirements.txt', 'pyproject.toml']
```

**Comment by mmarchetti** [comment]
We're switching to only bundling specified files (not using the `*` wildcard) in #2068, so we don't need to layer gitignore exclusions on top of that.
