### ISSUE TITLE
Support credential provided through environment variables

### ISSUE THREAD

**Issue by sagerb** [posit-dev/publisher#2062]
To provide initial support for Workbench, we have decided to support the specification of a server credential via environment variables. These are:

CONNECT_SERVER: the URL of the server
CONNECT_API_KEY: the ApliKey for the publisher
CONNECT_SERVER_NAME: <optional> the nickname of the server. If not specified, use the hostname of the server URL.

Do not allow the deletion of a credential specified via the environment variables.

Do not allow overlap of URL or Name with other credentials.

**Comment by dotNomad** [comment]
This ended up not being a solution in Workbench. It worked on desktops since the user space `.bashrc` was being sourced, but in VSCode on the web it doesn't work.

We are switching the behavior to what is described in #2088
