### ISSUE TITLE
Inspection not discovering `quarto-shiny` type

### ISSUE THREAD

**Issue by sagerb** [posit-dev/publisher#2065]
Was working with Garrett on using the publisher during demos at conf.

His repo projects: https://github.com/posit-dev/posit-conf-survey

He has multiple projects all stuck into one subdirectory.

Inspection of `dashboard.qmd` returned `quarto` but didn't return a choice of `quarto-shiny`. 

It also incorrectly detected that it required python, but it wasn't.

**Comment by dotNomad** [comment]
Verified functioning with `revealjs` Quarto doc.
