### ISSUE TITLE
Files: traverse subdirectories to find included files

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#2075]
The file walker doesn't visit subdirectories unless there's a matching file pattern to include them. But a pattern might match something within the directory, and we won't know until we look.

For example:
```
files = ['dashboard.qmd', 'responses.csv', '_extensions/jmbuhr/qrcode/_extension.yml', '_extensions/jmbuhr/qrcode/assets/qrcode.js', '_extensions/jmbuhr/qrcode/qrcode.lua']
```
will not include any of the files under `_extensions`.

**Comment by dotNomad** [comment]
Verified on `main`
