### ISSUE TITLE
Dependency scanning cannot reliably choose packages with different module names

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#2113]
For example:

[`python-dotenv`](https://pypi.org/project/python-dotenv/) has an import like:

```python
from dotenv import load_dotenv
```

and our scan will conclude that the package that should be included in the `requirements.txt` file is `dotenv`.

However the package name itself is `python-dotenv` and [`dotenv`](https://pypi.org/project/dotenv/) is a totally different package.

**Comment by mmarchetti** [comment]
This should work correctly if `python-dotenv` is installed locally before scanning, because Publisher looks at the installed package metadata to discover the import name -> package name mapping.

**Comment by kgartland-rstudio** [comment]
I've confirmed this does work if the `python-dotenv` package. I get `python_dotenv==1.0.1` added to my requirements.txt file. However if it's not installed I get `dotenv` added which I supposed is expected but just wanted to clarify here.

**Comment by mmarchetti** [comment]
Yes; that's the best we can infer without the package being installed (or a lookup table). You should see a warning in the extension (or CLI) recommending that you install the packages and try again.
