### ISSUE TITLE
When redeployment fails we can no longer update existing deployment

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#2119]
I have an existing successfully deployment. If I change my Python version to an invalid one and re-deploy, all Deployment history is lost and I can no longer update my deployment on the server.

STR:
* Create a deployment with a Python app
* Once it succeeds, update the config with an invalid Python version
* Redeploy so a failure occurs

The deployment history is cleared and I now have no way to update the existing deployment.  This seems to occur with any failure.

This instead should keep the Deployment history and allow me to update the existing deployment.

Example:

https://github.com/user-attachments/assets/0b7e97d8-7a6c-401e-ac15-fdfa549848d8

**Comment by dotNomad** [comment]
I believe this is fixed with the merge of #2133. @kgartland-rstudio can you confirm that you are no longer seeing this behavior?

**Comment by kgartland-rstudio** [comment]
Closing, can no longer reproduce.
