### ISSUE TITLE
Errors in configuration file results in confusing error

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#2120]
If I update my configuration file with an invalid field, I get the following error:

![Screenshot 2024-08-15 at 4 39 44 PM](https://github.com/user-attachments/assets/81e1360f-cebb-4a06-812a-43db2c6b5bc0)

Can we catch that error and throw an error about an invalid configuration file?

**Comment by dotNomad** [comment]
Let's retry this one too.

**Comment by kgartland-rstudio** [comment]
Cannot reproduce on latest `main` branch.
