### ISSUE TITLE
When the configuration file is deleted, clicking Create a Configuration link works but also throws an error

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#2122]
In a project where I have deleted the configuration toml file, I get the appropriate message with a link to `Create a Configuration` but when I click that link an error is thrown that reads:

```
Unable to retrieve deployment configuration: An error has occurred at getSelectedConfiguration, contentRecords.get, StatusText=Not Found, Code=ERR_BAD_REQUEST, Msg=404 page not found , URL=http://localhost:61962/api/get//configurations/configuration-1
```

I wouldn't expect that error to be thrown when I'm trying to create the configuration file. 

Note, this error is _not_ thrown when adding a configuration through the Select box.

Here's a video:

https://github.com/user-attachments/assets/f6e375f6-84f1-4dd4-b09f-11e677b6cfaf

**Comment by dotNomad** [comment]
Can we try this one again on `main`?

**Comment by kgartland-rstudio** [comment]
Cannot reproduce on latest `main` branch.
