### ISSUE TITLE
Bug: Selection of alternative configuration loses Deployment Selection

### ISSUE THREAD

**Issue by sagerb** [posit-dev/publisher#2131]
Reproduction steps appear to be:

1. Open the sample content directory in VSCode
2. Create 2 new deployments (`fastapi-simple/simply.py`). Alter config as appropriate and deploy
3. Select active configuration for second deployment, select an earlier one
4. Notice the active deployment is no longer shown and Select... is shown incorrectly.

**Comment by sagerb** [comment]
Looks like this is being caused by #2133

**Comment by dotNomad** [comment]
Just re-tested this and followed your reproduction steps. I wasn't able to recreate this issue. I'll go ahead and close this one up. If you, or anyone else, is able to recreate this we can re-open it.
