### ISSUE TITLE
Opening a directory with no detectable entrypoints throws confusing errors

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#2135]
When I open a directory with no detectable entrypoints, I'm able to click the `Select...` dropdown.  Three errors are thrown and the Create New Deployment dropdown still displays.  If I then click `Create New Deployment` then I get a fourth error saying an entrypoint cannot be detected.

Error 1:
 ```
An error has occurred at refreshContentRecordData::contentRecords.getAll, StatusText=Internal Server Error, Code=ERR_BAD_RESPONSE, Msg=open /Users/kgartland/.Trash: operation not permitted, URL=http://localhost:57521/api/get//deployments
```

Error 2:
```
An error has occurred at refreshAll::Promise.all, StatusText=Internal Server Error, Code=ERR_BAD_RESPONSE, Msg=open /Users/kgartland/.Trash: operation not permitted, URL=http://localhost:57521/api/get//deployments
```

Error 3: 
```
An error has occurred at refreshConfigurationData::configurations.getAll, StatusText=Internal Server Error, Code=ERR_BAD_RESPONSE, Msg=open /Users/kgartland/.Trash: operation not permitted, URL=http://localhost:57521/api/get//configurations
```

Error 4 (after clicking Create New Deployment):
```
Unable to continue with project entrypoint detection failure. An error has occurred at newDeployment, entrypoints.get, StatusText=Internal Server Error, Code=ERR_BAD_RESPONSE, Msg=open /Users/kgartland/.Trash: operation not permitted, URL=http://localhost:57521/api/post//entrypoints
```

Instead can we catch this earlier when the Publisher is displayed, throw Error 4 and make the `Select...` dropdown inactive?

**Comment by dotNomad** [comment]
This is pretty different from what I'm seeing when opening up an empty folder.

https://github.com/user-attachments/assets/4f6bf135-4e1e-44ef-9d65-91b672334613

Can you share a bit more about your environment here?

**Comment by dotNomad** [comment]
Looking at the errors it looks like the open workspace in VS Code and we don't have permissions to open the `.Trash` folder.

Should we just ignore directories that we don't have permissions for.

**Comment by sagerb** [comment]
>Should we just ignore directories that we don't have permissions for.

As discussed yesterday, yes, we should ignore them, but we want to log this action within the agent log.

**Comment by dotNomad** [comment]
Verified on `main` that we no longer get `operation not permitted` errors when we encounter a directory that we cannot read.

Tested by using `chmod 000` on a directory.
