### ISSUE TITLE
Include attributes for directories in files API if all nested files are included or excluded

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#2147]
For the hierarchical tree view with checkboxes we want to have the folders in the tree view to have an [indeterminate state](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate_state_checkboxes) so the three states are:

- Checked if all nested files are included
- Unchecked if all nested files are excluded
- Indeterminate if some nested files are included and some are excluded

To do this we can include attributes if all files are included and another if all files are excluded.

We could collapse these into a single attribute with different enum states as well. As long as we can determine the three states above.

**Comment by jonkeane** [comment]
> * Checked if all nested files are included
> * Unchecked if all nested files are excluded
> * Indeterminate if some nested files are included and some are excluded

This works, and might be the most natural interpretation abut there is also a slightly different mapping we could use: 

* Checked if the folder itself is included (which IIUC means that all files under that are included too, e.b. `foo/bar`)
* Unchecked if no files under that directory are ever included
* Indeterminate if any set of files are included with a path (`foo/bar/baz` or `foo/bar/baz,foo/bar/qux`) regardless of if all of the files happen to be included or not

This matches the text of the inclusions slightly more which might be nice.

**Comment by dotNomad** [comment]
> This matches the text of the inclusions slightly more which might be nice.

Great breakdown. I think this is much better.
