### ISSUE TITLE
Bug: Some RMDs are not able to be rendered with Quarto

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#2155]
See conversation: https://positpbc.slack.com/archives/C05D7NZD52S/p1724253867791419

**Comment by kgartland-rstudio** [comment]
Closing, this is a user-error. If you're using output: `html_document; runtime: shiny` It requires library(shiny) to work properly.

https://github.com/quarto-dev/quarto-cli/discussions/10579
