### ISSUE TITLE
Windows: When a failure occurs, clicking "Edit Configuration" throws an error

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#2175]
In Windows, if an error occurs I get a button to `Edit Configuration` but when I click it the following error is thrown and the configuration does not open:

> The editor could not be opened due to an unexpected error: Unable to resolve resource c:%5CUsers%5Ckevin%5Cpublisher-git%5Ctest%5Csample-content%5Caddfiles%5C.posit%5Cpublish%5Cconfiguration-1.toml

**Comment by dotNomad** [comment]
Which "Edit Configuration" button exactly has this issue?

Does the Edit Configuration button above the selector (the pencil / pen icon) have the same issue?

**Comment by kgartland-rstudio** [comment]
Oh sorry, the Edit Configuration button that appears in the error message in the lower-right corner. The edit configuration link in the webview does _NOT_ have the same issue.

It's this button:
![Screenshot 2024-08-26 at 1 39 21 PM](https://github.com/user-attachments/assets/84367461-8364-449b-a46c-29093a4861e3)

**Comment by dotNomad** [comment]
@sagerb we may want to take a look at this one for Beta 6.

**Comment by dotNomad** [comment]
`EvenEasierDeploy` does:

```
onEditConfiguration(home.selectedConfiguration!.configurationPath)
```

Which sends the `WebviewToHostMessageType.EDIT_CONFIGURATION` message that does

```
    await commands.executeCommand(
      "vscode.open",
      Uri.file(msg.content.configurationPath),
    );
```

So ultimately we are opening `Uri.file(home.selectedConfiguration.configurationPath)`

---

In `posit.publisher.homeView.edit.Configuration` we do

```
commands.executeCommand(
  "vscode.open",
  Uri.parse(config.configurationPath),
);
```

So maybe the answer is to switch from `Uri.parse` to `Uri.file`?

**Comment by sagerb** [comment]
thanks @dotNomad for looking into this, I totally agree and will implement that specific change.
