### ISSUE TITLE
nit: When renv.lock file is not available an uninformative error is thrown

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#2177]
Since we now include `renv.lock` by default for all R content in the `files` array, an error is thrown that doesn't explain _why_ we're looking for a renv.lock file.  I think this would be confusing, especially to users who don't use renv regularly.  My first instinct would be to simply remove it from the config. 

> Deployment failed: open c:\Users\kevin\connect-content\bundles\deploy-err\renv.lock: The system cannot find the file specified.

I wonder if we can detect that there is no renv.lock file in the target directory and disabling the Deploy button with a clear error.

**Comment by dotNomad** [comment]
There is probably a similar error for the `requirements.txt` when it is missing, and we can improve the errors for both when those files are missing.

**Comment by mmarchetti** [comment]
We will prevent this by showing the error indicator / message and preventing Deploy.

**Comment by jonkeane** [comment]
> We will prevent this by showing the error indicator / message ~and preventing Deploy.~

**Comment by jonkeane** [comment]
> Just to clarify your comment/reaction above, we just want to improve the error messages here, but, inline with our latest decisions, we'll still allow a deployment to be initiated.

Yup, exactly
