### ISSUE TITLE
Add Content Type selector to new config flows where inspection returns "unknown"

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#2200]
This will prevent the creation of `unknown` configurations, that have downstream impacts.

**Comment by sagerb** [comment]
Tried to implement the approach, in which we attempted to set the content type within the inspection results (which returned with a type of unknown). We did this as part of the new deployment flow, but when we attempted to have the agent save the configuration we were passing it, it was invalid according to the schema. Each type has some additional field requirements which are not set in the unknown inspection result, so it requires additional values before the API could save it out.

Not sure how we're going to be solving this, but this technique as outlined won't work. We created issue # to track.

Closing this as not planned.

**Comment by sagerb** [comment]
Not planned.
