### ISSUE TITLE
You don't have to show me every file in .git in Excluded Files

### ISSUE THREAD

**Issue by nealrichardson** [posit-dev/publisher#2207]
![image](https://github.com/user-attachments/assets/776b5f5e-77e9-4438-b505-19487347ce6b)

**Comment by dotNomad** [comment]
😆 Agreed. Similar to #2208 this will change quite a bit in the next release (`1.1.6`) coming in a day or two.

With Project Files becoming a hierarchical tree, we show the `.git` directory collapsed with a checkbox indicating whether or not that folder is included or excluded from the deployment.

I'll leave this open and check back in when `1.1.6` is released to see if the new Project Files view addresses this feedback.

**Comment by dotNomad** [comment]
`1.1.6` has been released. Check out the new Project Files view, and let us know if it solves this bit of feedback for you. If you have any new feedback on the release we'd love to hear it.

**Comment by nealrichardson** [comment]
Yes thanks!
