### ISSUE TITLE
If I click "PROJECT FILES", automatically open "Included Files"

### ISSUE THREAD

**Issue by nealrichardson** [posit-dev/publisher#2208]
I shouldn't have to click twice to see what's included.

**Comment by dotNomad** [comment]
Thanks for the feedback. This should change quite a bit in the next release (`1.1.6`) coming in a day or two.

We addressed some early feedback in issue #1210 (with PR #2097 and #2168) and made Project Files a hierarchical tree that is automatically expanded. It shows base files and directories with checkboxes indicating if they are included in the deployment or not.

That reduces the clicks down to zero, and makes it more prominent in the "review prior to deployment" stage.

I'll leave this open and check back in when `1.1.6` is released.

**Comment by dotNomad** [comment]
`1.1.6` has been released. Check out the new Project Files view, and let us know if it solves this bit of feedback for you. If you have any new feedback on the release we'd love to hear it.

**Comment by nealrichardson** [comment]
Yes, much better, thank you!
