### ISSUE TITLE
I don't know what "Deploy with this Entrypoint" means

### ISSUE THREAD

**Issue by nealrichardson** [posit-dev/publisher#2209]
It's the hover text on 
![image](https://github.com/user-attachments/assets/9bd62f2e-025e-4b39-9923-8facc275266c)

Maybe "Deploy to [server name]" instead?

**Comment by mmarchetti** [comment]
It means something like "Deploy this file", maybe we can use that?

**Comment by nealrichardson** [comment]
Oh, I know what it means, I was channeling my inner new-user and calling out things I saw that look weird from the outside. 

I'd check what other extensions do in this area. "This File" might be standard messaging, or it might be assumed and thus not shown.

**Comment by dotNomad** [comment]
We can adjust the test to "Deploy with Posit Publisher" to match the wording on other Editor buttons while removing the "Entrypoint" term which may not be known.
