### ISSUE TITLE
Provide better context / direction to users when we fail with 500 errors.

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#2216]
Created from this thread: https://positpbc.slack.com/archives/C05D7NZD52S/p1724869923716389

**Comment by mmarchetti** [comment]
Depends on #2193

**Comment by jonkeane** [comment]
Is this still relevent?

**Comment by dotNomad** [comment]
> Is this still relevent?

I'm sure there are still some lingering flows where it possible to get a 500 error. Rather than auditing all of the catches in the frontend that display errors to users though, it would be much more efficient to handle them as individual issues as they come up.
