### ISSUE TITLE
I see multiple accordion headers for Help and Credentials

### ISSUE THREAD

**Issue by nealrichardson** [posit-dev/publisher#2238]
![image](https://github.com/user-attachments/assets/6b6541d6-a9b4-491c-9d0b-718f5382b0de)
 
I just upgraded to 1.1.6. This is in Positron `2024.08.0 (Universal) build 48`.

The bottom ones seem pinned to the bottom and open up. The other ones open down. Happy to screenshare if it helps.

**Comment by dotNomad** [comment]
It looks like VS Code is remembering the old views despite them being removed in the newest version of the extension. I confirmed they are actually removed from the `contributes` list.

A quick search didn't find anything about clearing those out, but here are a few ideas to try:
- "Reload Window" (can be found via the command palette)
- Hide the views via the `...` menu in the top right of the sidebar and uncheck them in Views to see if they get removed both visually and from the list
- Uninstall and reinstall the extension

I'd be happy to jump on a screen share to help debug this.

**Comment by nealrichardson** [comment]
Ah ok, "Reload Window" worked. Thanks!
