### ISSUE TITLE
Confused "select new or existing" dialog

### ISSUE THREAD

**Issue by nealrichardson** [posit-dev/publisher#2241]
![image](https://github.com/user-attachments/assets/9adbfc59-0ce6-4842-827b-09cdb5bdfa10)

I think there are two different issues in here.

1. I have a project with a bunch of subdirectories. I had used an old version of Publisher to publish some of them by opening new windows in the subdirectories--this was back when Publisher didn't support subdirectories. For whatever reason, when I open this project now (in the top-level directory), none of the previously published things are found. I don't know whether you expect this to work or not; if not, that's fine, I'm an edge case not worth worrying about.
2. Assume this is the first time I'm publishing in a project--I've confirmed that it looks the same in a fresh project. The buttons and dialogs should be aware of the fact that there are 0 configs/deployments. How can I select an existing deployment? Why invite me to "pick one of the existing deployments below" when there are none?

**Comment by mmarchetti** [comment]
Using this issue for #2 (buttons and dialogs should reflect when there are no existing deployments). Opened #2249 for our investigation into #1.
