### ISSUE TITLE
Add action indicators to section headers to indicate that attention is needed

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#2245]
- Add ability to show icons in the TreeSection headers
- Show warning icons in headers when that section has a warning
    - Like a missing package file

**Comment by dotNomad** [comment]
Confirmed that:
- having no `requirements.txt` (package file) when Python is configured shows a warning codicon
- having no `renv.lock` (package file) when R is configured shows a warning codicon
- having no credential for the selected deployment shows a warning codicon
