### ISSUE TITLE
Disable the deployment button when there are issues detected by the publisher

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#2247]
This will force the user to resolve the issue ahead of the problem occurring during deployment.

When the button is disabled, the tooltip should be updated to indicate the issues must be resolved first.

**Comment by jonkeane** [comment]
I'm supportive of this in principle, but we need to be careful about how we implement this and make sure that we're not locking folks out for things that we _think_ are errors, but are actually just fine. Or give someone an escape hatch that lets them confirm "this might not work, but you can try". 

Similar in spirit to how we will need to make sure that allegedly unrecoverable errors don't block everything (e.g. #2069 #2216 which are still open, #2103 is closed, but is an example of where that bit us)
