### ISSUE TITLE
Make the entrypoint file more prominent within the deployment selector

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#2248]
Currently the entrypoint file is shown, but appears less significant than the deployment (which is showing title and credential nickname).

Since the entrypoint is the top-level object in a deployment, we need to show it as more prominent. One idea is to update the select button to show it ahead of the title (perhaps with 3 lines), or place it on the same line as the credential. (But horizontal space is limited, so we should probably explore 3 lines first.)

When this is changed, we should also examine how the multi-selector can also show the entrypoint as part of the 2 line entry for each deployment, so that the concepts are consistent.

**Comment by sagerb** [comment]
Group decided to:
- Update multi-select entries to include entrypoint (as part of project dir segment)
- Add entrypoint name to top of deployment selector
