### ISSUE TITLE
Existing deployments from an earlier beta not found

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#2249]
I have a project with a bunch of subdirectories. I had used an old version of Publisher to publish some of them by opening new windows in the subdirectories--this was back when Publisher didn't support subdirectories. For whatever reason, when I open this project now (in the top-level directory), none of the previously published things are found. I don't know whether you expect this to work or not; if not, that's fine, I'm an edge case not worth worrying about.

**Comment by jonkeane** [comment]
We should be judicious about how much effort we put into this. Neal is right with:

> if not, that's fine, I'm an edge case not worth worrying about.

It would have been great to _not_ have this friction, and we should make sure that we don't do it again in the future, but I don't think we should put too much effort into fixing this going forward. If it's easy and quick, sure; but we've already broken a thing and that's part of the reason we had the alpha label for so long was we were worried we might do this.

**Comment by mmarchetti** [comment]
Agreed. We put this in for investigation in case it's a real issue that only happened to surface in this way.

**Comment by dotNomad** [comment]
We marked the Publisher as pre-release to avoid worrying about these issues. Once we are out with `v1.2.0` we will need to worry about things like this.
