### ISSUE TITLE
Secrets: New UI panel for Secrets

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#2252]
Create a new collapsible panel at the same level as Python packages, R Packages, etc. It shows the list of secrets from the configuration, with an indicator showing whether each one has been loaded in the current session.

**Comment by jonkeane** [comment]
> with an indicator showing whether each one has been loaded in the current session.

I'm not sure I follow what you mean by this, could you expand a bit more? Loaded to where? What session?

**Comment by mmarchetti** [comment]
The data flow for secrets in the initial implementation is:
* they live in a .env file (we exclude .env files from the deployment file list by default, to avoid accidentally sending them)
* when the user loads them via the extension UI, the UI now holds the secrets
* the UI sends the secrets with the request to initiate the deployment
* when the deployment succeeds, or the user changes the UI state to a different deployment, the UI clears the currently loaded secrets
