### ISSUE TITLE
Reword prompt for Credential Nickname

### ISSUE THREAD

**Issue by sagerb** [posit-dev/publisher#2265]
https://positpbc.slack.com/archives/C05D7NZD52S/p1726065183528269

![Image](https://github.com/user-attachments/assets/bcb7a2a9-371e-4da3-8810-e7e9f052be99)

The Title Case is awkward here, and the “Credential” concept was not previously introduced. Consider saying something a little more casual like:
Enter a unique nickname for this server and API key combination.

**Comment by dotNomad** [comment]
Adding another example of the inputs from VS Code to show that the title case is usually not used

![CleanShot 2024-09-12 at 13 58 45](https://github.com/user-attachments/assets/d53f0d68-f974-444d-936e-791752fd6405)
