### ISSUE TITLE
Quarto Website not deploying as expected

### ISSUE THREAD

**Issue by sagerb** [posit-dev/publisher#2266]
## Update (while trying to reproduce)

While trying to reproduce this issue, found that the work for enabling Quarto scripts (#2424) also helped on Quarto websites, with a couple items still requiring work:
1. Pre and Post render scripts are not automatically picked up to be added to the configuration on project inspection
2. Users selecting `_quarto.yml` as entrypoint would get an undesired outcome (`unknown` type project). This because `quarto inspect` does not work on `_quarto.yml` files but it is understandable that the user picks that file and by doing so the project type is explicit enough already.

## Original

From: https://positpbc.slack.com/archives/C05D7NZD52S/p1726064950810009

I have a Quarto website project. I don’t really understand what needs to be considered the “entrypoint” in this context. I’m given my *.qmd files, my *.py pre-render script, and one rendered HTML file, but the _quarto.yml file (which is the closest option in my mental model) isn’t offered.

![Image](https://github.com/user-attachments/assets/e89fc199-49f6-4061-ad65-06655cf6c7cf)

I want to deploy this project as source (not rendered) and include the files:
- _quarto.yml
- requirements.txt
- index.qmd, visualize-r.qmd, visualize-py.qmd
- allocation.py
This project has both R and Python package requirements.

Proceeding with the deployment workflow, it missed the pre-render allocation.py script and did not identify that the project requires R as well as Python.
The Quarto inspect output DOES say that knitr is used:
```
  "engines": [
    "jupyter",
    "markdown",
    "knitr"
  ],
```

I tried to guess about the [r] syntax:
```
[r]
version = '4.3.3'
```

 I got an ugly error (attached).
The TOML was updated with placeholders which also violated the configuration:
```
[r]
version = '4.3.3'
package_file = ''
package_manager = ''
```

![Image](https://github.com/user-attachments/assets/f1b647b9-321f-4986-a518-ea2e4cdba9ef)

I tried to `package_manager = 'none'` and got a complaint when trying to deploy; I was trying to use my standard library, not renv.

![Image](https://github.com/user-attachments/assets/9bcee1db-469f-4dbc-96c1-8f2cc6c11b74)

:cry: The deployed manifest does not indicate that Quarto needs the knitr engine and therefore does not cause Connect to install R packages.

```
	"quarto": {
		"version": "1.5.57",
		"engines": [
			"jupyter",
			"markdown"
		]
	},
```

For those following along, I was able to successfully deploy with:
```
rsconnect::deployApp(server = "rsc.radixu.com", account = "aron", python = file.path(getwd(), "env/bin/python"))
```

This one is a little awkward because it doesn’t use reticulate. Instead, it uses both the knitr and jupyter engines. rsconnect could do better at detecting the need for Python in this situation.

Note: I still have `package_manager = 'none'` but renv was required.

See slack link for archive of project, created with:
```
tar cf mixed.tar --exclude mixed/_site --exclude mixed/env --exclude mixed/renv/library --exclude mixed/.quarto mixed
```

My Python virtual env was in `env`.

**Comment by aronatkins** [comment]
There are a few different problems here:

1. The concept of "entrypoint" is vague for a Quarto website, and the `_quarto.yml` file is not offered.
2. The `knitr` engine did not imply the use of R (discovered prior to renv initialization)
3. `r.package_manager = 'none'` was not the default and did not appear to be respected.
4. R dependencies were required and shared in the manifest.json, but `quarto.engines` lacked `knitr`.

**Comment by sagerb** [comment]
After discussion with Jon, we'd like to try and mimic the behavior that the IDE has for quarto websites in which a subselection of the website or quarto doc is automatically changed to be the entire website or doc. It is at this post-configuration location, that the quarto utilities should be run from, which then should provide the proper functionality. This would remove the issue with Quarto as to the user picking the wrong project entrypoint.

We'll also, obviously, need to allow the selection of the `_quarto.yml` file as the project entrypoint.
