### ISSUE TITLE
Canceling while creating a Deployment results in an error

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#2281]
If I start a deployment but hit Esc before entering the credentials, this error is thrown:

```
Internal Error: NewDeployment Unexpected type guard failure @1
```

https://github.com/user-attachments/assets/098a3dd9-c0d8-4469-acbc-6bc766d027fa

**Comment by sagerb** [comment]
I am unable to reproduce this with the code on `main`.

I believe I fixed this recently, so it didn't just "magically" go away. @kgartland-rstudio would you mind re-testing, and letting me know if you are able to reproduce it?

Thanks!

**Comment by kgartland-rstudio** [comment]
I can no longer reproduce. Closing...
