### ISSUE TITLE
Secrets: UX confusion

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#2298]
I was a bit confused while testing the Secrets UI.  I now understand how to use it, but it did require some tinkering and more advanced configuration usage that we haven't yet introduced.  Here are some things I ran into. I'm filing this as an enhancement because these aren't really "bugs" as I think it's working as-designed.

1. nit: the clear button is loaded and active even when there are no secrets to clear:
<img width="660" alt="Screenshot 2024-09-23 at 10 28 43 AM" src="https://github.com/user-attachments/assets/b3566c2e-93a0-4396-a97f-5f057194fd2a">

2. UX: it's not clear _how_ to add a secret. I expected there to be an add button to create one from the UI.  This differs from something like `title` because we include `title` in the config by default so users know they can update that. `secrets` are not included and it's also unclear that it takes an array. I think first-time users will have a hard time understanding how to use this feature.  Maybe since this is more of a code-first element, we should add an example to the config via a commented out secrets field? 

3. When I _do_ add the secret to the configuration file, it's not clear that I then have to edit it to add a value. The edit pencil only appears when you hover over the newly created Secret.  My initial thought, is by clicking the edit pencil, it would prompt me to update the title rather than add a value.

4. After I populate my configuration with an array of Secrets, I can click the Clear icon, but I expected it to clear the actual Secrets rather than the values.

I think most of the confusion at first blush is due to the field operating differently than other fields available in the interface. The other fields allow interaction with the configuration file, but this is a step in "code-first" that we haven't yet introduced.  

For example, the Title is created in the UI and adds it to the configuration file.  The Project files can be added/removed from the configuration via the UX.  Whereas the Secrets field forces the user to first add the secret to the configuration file and any subsequent UI interaction updates the configuration file.

**Comment by dotNomad** [comment]
Split out some of the work into #2304 and #2305

The callout in point 3 where the UI isn't quite clear since it is so different from other elements we plan to do some user testing to flesh out exactly how we should address that.

**Comment by dotNomad** [comment]
Closing this one since work has been split out, and new issues will be created based on user testing.
