### ISSUE TITLE
Import: When deploying to a mismatching content type, metadata is updated but deployment fails

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#2301]
As a test I tried to deploy a bokeh app targeting an already-deployed fastapi app on the dogfood server.

1. The Deployment Status briefly shows the deployment succeeded and then flips to failure:

https://github.com/user-attachments/assets/ad257b4a-76d2-448c-8e55-32d9e91a5818

2. The title (and other metadata included in the configuration file) for the content on Connect was updated even though the deployment failed.

I would expect this to fail earlier so we don't update the content on Connect.  Can we detect what target content type is before we even start the deployment? I think we're making the api calls on Connect to update the metadata before the call to do the deployment.  Maybe these should be in the reverse order?

STR:
* Deploy a fastapi app to Connect
* Now deploy a bokeh app using the new `update that previous deployment` link and point to the previous app URL
* I'm allowed to deploy the app
* The Deployment shows Success briefly but then displays the Failure
* The target app's metadata was updated even though the deployment failed.

Expected:
I would expect...
* that we detect a mismatching content type prior to the deployment
OR
* the deployment fails, never shows a success message and the metadata to remain unupdated

**Comment by kgartland-rstudio** [comment]
Probably related:
In the standard redeployment flow, again the metadata gets updated when the deployments fail.

STR:
1. deploy the fastapi example successfully
2. update the simple.py so that it will fail
3. change the title to see if the metadata updates
4. deploy

The title updates even though the deployment fails.

**Comment by sagerb** [comment]
> 2\. update the simple.py so that it will fail

@kgartland-rstudio I believe the scenario you're describing here differs from this issue. I believe that even if the redeployed content did not run successfully, the title and other metadata required to be in place before running would have been updated.

Am I following your comment correctly or perhaps missing something?

**Comment by kgartland-rstudio** [comment]
> I believe that even if the redeployed content did not run successfully, the title and other metadata required to be in place before running would have been updated.

The title and other metadata from the original deploy, yes those would be up and running prior to the redeployment, but if you update the title in your config and update the app so it's now broken, the title will still get updated even though the deployment actually failed.

I'm not sure if that's a bug or not but it seems unexpected.

**Comment by sagerb** [comment]
>even though the deployment actually failed.

@kgartland-rstudio I see it as two different things, but perhaps I'm not viewing it as a user would. 

The publisher's deployment will report failed because the publisher code was unable to verify the application could run. This would typically have been due to a code error, as your example shows. It could also be an issue with missing environment variables, or even failed API calls out to external resources.

Is your observation because we have chosen to include a step in which we attempt to run the application and at least verify that it will run on the server (and if it fails, show this as a deployment error)?

**Comment by kgartland-rstudio** [comment]
I don't think user's think a deployment is a series of API Calls, some succeeding and others failing.  I would expect if a deployment failed, all the metadata that i included would fail as well.  Maybe that's just me? I'm not sure.

I tried it out in RStudio, but they actually don't let you update the title on a redeploy.

In rsconnect-python it _does_ update the title even if the deployment failed.  

FWIW, I don't think this case is as important as the original mismatching content issue, because when deploying to a _different_ target content, users can update or break content very easily.

**Comment by sagerb** [comment]
It totally makes sense to think of deployment or re-deployment as a transactional operation, where if something fails, nothing is changed on the server. Unfortunately, that's not the way Connect works at this point.

I talked with Jon and he said that Connect does have a feature identified which will provide some capabilities in this area to improve the scenario. When Connect supports a solution, we'll then want to work it into the Publisher.

It would be best to have this second issue to be broken out into a separate one, if you'd like to continue exploring a better option for it. 

I am moving forward on the original issue. Thanks!
