### ISSUE TITLE
Long file paths get truncated in the Discovered Entrypoints dropdown

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#2303]
This may be moot, as I think Bill mentioned he's planning on updating this dropdown menu to a file selector, but I just noticed this...

When I have a long file path, it can get truncated in the dropdown, can we show the full path on hover?

Here's what I'm seeing and hovering doesn't show the full path:
<img width="614" alt="Screenshot 2024-09-24 at 10 10 43 AM" src="https://github.com/user-attachments/assets/bf4924b5-e901-49ae-b0bb-6ef6491f1b95">

**Comment by dotNomad** [comment]
Closing this one up as not planned. The new implementation makes this less likely, its pretty rare already, and requires a very high level workspace.
