### ISSUE TITLE
Refresh File List API errors being displayed when editing and saving an invalid active configuration file.

### ISSUE THREAD

**Issue by sagerb** [posit-dev/publisher#2323]
API calls which depend on a valid configuration file are being called even if the configuration file is in error, which causes API failure notices to be displayed in VSCode.

The following example is after I added an `[r]` section to the configuration file and saved the file.

![Image](https://github.com/user-attachments/assets/4b14f676-436e-4e80-8b0b-f38885761942)

This particular issue would be resolved if we suppressed the API calls which require a valid configuration are suppressed if we know it is error.

Also notice that the configuration dependent sections are visible when the active configuration is in error - which is not reliable (since the backend can't read / parse the invalid configuration file).

**Comment by dotNomad** [comment]
Confirmed that I'm not getting the errors when adding an error to the selected configuration, or removing said error.
