### ISSUE TITLE
Error 500 reported if renv.lock is empty file

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#2327]
To reproduce, open an R Project deployment and delete the contents of the renv.lock file.

![Image](https://github.com/user-attachments/assets/4f2986a7-49d4-4485-8913-53ccaf51ebbc)

**Comment by marcosnav** [comment]
While investigating and replicating, found out that an empty `renv.lock` file while creating a new deployment also shows a 500 error message halting the new deployment creation

**Comment by jonkeane** [comment]
> While investigating and replicating, found out that an empty renv.lock file while creating a new deployment also shows a 500 error message halting the new deployment creation

😱 Yikes

**Comment by marcosnav** [comment]
Interesting that the R Language Server also errors due to empty `renv.lock`
![Image](https://github.com/user-attachments/assets/5b984180-1a1e-4058-9897-65ccaccc9d93)
