### ISSUE TITLE
Add support for retrieving environment variables from Connect

### ISSUE THREAD

**Issue by sagerb** [posit-dev/publisher#2365]
This will include extending `connect_client` within the agent and supporting a new API to be accessed from UX.

Retrieve the list of environment variable names defined for this content item w/
> GET /v1/content/{guid}/environment

source: [API documentation](https://docs.posit.co/connect/api/#get-/v1/content/-guid-/environment)

will return a list of environment variable names, without values.
```
[
"DATABASE_URL",
"DEBUG"
]
```

**Comment by dotNomad** [comment]
Idea for the wording on the warning above the deploy button:

> A Secret is required for this deployment, but does not have a value set.
> SECRET_NAME

**Comment by dotNomad** [comment]
Some additional suggestions are to use `cloud-upload` for secrets that have values set to send up, and show the `***` value if the secret has a value (on the server or set to send up)

![Image](https://github.com/user-attachments/assets/f75853ff-d523-465a-b040-bfa26234d466)

**Comment by dotNomad** [comment]
Additional improvement from the thread. Using `check` for Secrets already satisfied on the server.

![Image](https://github.com/user-attachments/assets/b6526bea-a377-481b-a341-e101bb0e402d)
