### ISSUE TITLE
Include configuration (and deployment?) file by default when deploying?

### ISSUE THREAD

**Issue by jonkeane** [posit-dev/publisher#2370]
We used to include this by default when we included everything, but we don't anymore. We probably should include these by default when deploying (but allow folks to _not_ send them if they really do not want to). If we include them, so long as someone pulls a bundle from connect they can start working with it (and redeploy to the same place because of that).

Are there any reasons not to?

**Comment by dotNomad** [comment]
Completely agree!

The `.posit` directory is designed to be shared so I don't think we need to worry about including it. The only time that isn't true is if you have multiple deployments - one you intend to share, and one you don't.

Weighing those two I think the default, deployed bundle being a lot more usable with Publisher is more important.

**Comment by dotNomad** [comment]
Thinking about this a little more we could _only_ include the configuration itself and the related deployment in the `files` array rather than doing a wildcard like `.posit/publish/**` to get the benefit without the downside I mentioned above.

**Comment by jonkeane** [comment]
> Thinking about this a little more we could only include the configuration itself and the related deployment in the files array rather than doing a wildcard like `.posit/publish/**` to get the benefit without the downside I mentioned above.

Yeah this sounds like the right way and with the multiple deploy scenario, even if it's ok to share both / all it would be a bit confusing "I got this bundle form here, but it also references these others?"

**Comment by dotNomad** [comment]
Explored how to accomplish this and created a draft PR to start discussion: #2380
