### ISSUE TITLE
Unfriendly error when deploying with invalid TOML

### ISSUE THREAD

**Issue by kgartland-rstudio** [posit-dev/publisher#2374]
Since we can now deploy content with an invalid configuration file, unfriendly errors are thrown.

Example:
I have an error in my configuration file and the proper warning is displayed in the Home View.

![Image](https://github.com/user-attachments/assets/9a6ddbf9-6b5c-466e-bf30-aecb53f6bfef)

However when I try to deploy with that invalid configuration file I get this error:

> Failed to deploy . An error has occurred at homeView, deploy, Status=400, StatusText=Bad Request, Code=ERR_BAD_REQUEST, Msg=Bad Request: /Users/kgartland/work/publishing-client/test/sample-content/fastapi-simple/.posit/publish/fastapi-simple-0ARR.toml:18:7: expected = after a key, but the document ends there , URL=http://localhost:53562/api/post/deployments/deployment-NU2B

Can we throw a cleaner error here?

**Comment by sagerb** [comment]
Fix with a preflight error, similar to config warning.
