### ISSUE TITLE
Jupyter Deployment without displaying code

### ISSUE THREAD

**Issue by huste-illvkw** [posit-dev/publisher#2399]
Whilst deployment using `rsconnectdeploy`  supports the parameter `--hide-all-input`, I cannot find a similar option in Posit Publisher. 

```[tasklist]
### Acceptance Criteria
- [ ] Support the `rsconnect deploy` option `--hide-all-input`
```

**Comment by dotNomad** [comment]
Thanks for checking out Publisher, and letting us know that you'd find the hide all input functionality from `rsconnect` helpful!

After digging in this looks like something we can get into the next release of Publisher. 🎉

**Comment by dotNomad** [comment]
`1.4.0` has been released! 

Now the configuration file supports an optional section - `[jupyter]` - which allows for `hide_all_input` or `hide_tagged_input`.

```
[jupyter]
hide_all_input = true
```

Adding the above into your configuration should give you the same behavior as `--hide-all-input`.

Thanks again for opening an issue 🙇
