### ISSUE TITLE
Positron > Positron Pro

### ISSUE THREAD

**Issue by AshleyHenry15** [posit-dev/publisher#2456]
Due to licensing, we had to change Positron to Positron Pro when discussing Positron Sessions in Workbench (very similar to RStudio vs. RStudio Pro).

I just wanted to flag it here in case there is any cross-over.

**Comment by dotNomad** [comment]
Double checked and all mentions of Positron are about the IDE and are not referencing sessions in Workbench.

Thanks for flagging it here so we could take a look. Closing. 👍
