### ISSUE TITLE
Update R Inspection to use active R version to populate inspect results rather than renv.lock version

### ISSUE THREAD

**Issue by sagerb** [posit-dev/publisher#2464]
The publisher agent currently populates the `R.version` configuration field with the version found within the `renv.lock` file if it exists. This version is used to target the runtime R version used on Connect.

When a user creates a deployment for a project where the active R version being used within the IDE (VS Code or Positron) matches the version found  in `renv.lock`, all is well.

However, when a user who has configured a specific version of R to be used within VS Code or Positron (which can affect all of the visible and background R processes run within VS Code or Positron), starts interacting with a project who's `renv.lock` file is different, then we are setting up a scenario in which the intended remote execution may not operate as expected. 

To expand upon this scenario, let's suppose that the `renv.lock` file was last used with R version `4.3.3`, but the user has configured their IDE (VS Code or Positron) to use R version `4.4.2`. In this environment, when the user launches an R console, it will be run using the R Version configured (in this case, `4.4.2`). Operations will be run within that environment, including package installation and removal. `renv` will operate in that environment and will detect that having a `renv.lock` file of `4.3.3` but an active running R version of `4.4.2` is an environment which is considered "out-of-sync". `renv` operations will attempt to update the lock file to the same version as the running R console. In almost all cases, to get a successful deployment, the user will migrate the `renv.lock` file to version `4.4.2`.

In addition, the behavior of the Posit publisher will be to use the active version of R to populate the package details needed in the manifest every time the project is deployed. So unless it is caught, package versions of the dependent packages, valid for the active version of R within the IDE, will be used for a runtime time environment on the server that is matched against the incorrect version originally found in the `renv.lock` (`4.3.3`) during inspection. While this might work sometimes, it is not a close representation of the working environment of `4.4.2` running within the IDE.

This issue can easily be fixed by simply eliminating the agent code which attempts to populate the version found in the `renv.lock` file. When a version could not be found (or the `renv.lock` file did not exist), the code already drops down into using the active version of R for the IDE. If not set through an extension, it will fall through and use the first R interpreter it can find on PATH.

At this time, we do not have anything which will indicate that the R version loca

**Comment by sagerb** [comment]
Closing as we'll be implementing an updated issue: #2468 .

**Comment by dotNomad** [comment]
Marking this as a duplicate just for easier board management.
