### ISSUE TITLE
Add code coverage CLI checks for home view

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#2488]
Utilizing Vitest we can setup code coverage reporting, and CLI checks to fail when we do not hit thresholds.

**Comment by dotNomad** [comment]
Vitest has a setting which can auto update threshold values when code coverage is improved: https://vitest.dev/config/#coverage-thresholds-autoupdate

It could be possible to commit that if those change in a PR when `vitest` is run 🤔

**Comment by m--** [comment]
Related to https://github.com/posit-dev/publisher/issues/58 ? or does this supersede that one?
