### ISSUE TITLE
Implement rExecutable discovery to prefer the active version of R within the IDE rather than path

### ISSUE THREAD

**Issue by sagerb** [posit-dev/publisher#2500]
The code needs to identify the same version of R that the users have configured. This is passed in from the extension, but the backend code does not use this value consistently. To solve this, we need to make sure the correct path is identified, following our rules:
 
1. Use the passed-in path for the R interpreter if supplied. It must exist and be validated)
    - If it doesn't exist, fall through to the next option
    - If it does exist but is not a valid R interpreter (use `--version` output to validate), then return an error
 2. Use the first R executable found on PATH; it must exist and be validated.
    - If not valid or doesn't exist, return an error

Once the interpreter is identified, it should be used for creating/retrieving the lock file.

**Comment by dotNomad** [comment]
Verified that creating deployments creates configurations with the correct `r.version` set. The active interpreter is used in Positron to run our inspection as well.
