### ISSUE TITLE
Filter SSEs by `localId` for in progress publish

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#301]
Our Server Side Events contain, inside of their `data` property, a `localId` that tells us which publish it correlates with. When doing `POST` to `api/publish` we get a `local_id` back like this:

```
{"local_id":"xZYdw1Hpdw8EymEU"}
```

We can use this `localId` to filter out any SSEs that aren't related to the current, in-progress publish to avoid showing the user events that aren't related in the progress view.

```[tasklist]
### Acceptance Criteria
- [ ] Filter SSE by `localId` in the progress view
```

**Comment by mmarchetti** [comment]
This is already implemented in 1.1.5.
