### ISSUE TITLE
Unify API endpoint list behavior

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#510]
We currently have a mix of endpoints that return arrays and ones (like `/api/accounts`) that return an object with an `accounts` key that contains the array. We should unify this for consistency.

**Comment by dotNomad** [comment]
It looks like this is complete. After some investigation the `/api/accounts` API endpoint no longer has the `accounts` wrapping object, and returns an array. Other endpoints do the same where appropriate. Closing this one up.
