### ISSUE TITLE
Files API errs if an invalid file is in the directory

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#658]
Ran the agent in Positron, with our repo directory open. The UI showed a fatal error and this was in the agent log:

```
time=2023-12-19T10:09:50.256-05:00 level=ERROR msg="Internal Server Error" method=GET url=/api/files error="the file type for file /Users/mike/rstudio/publishing-client/internal/bundles/testdata/symlink_test/bundle_dir/fifo is not supported"
```

Most users are unlikely to have fifos in their project directories.

**Comment by jonkeane** [comment]
A lot has changed here, can re-open if we see it again
