### ISSUE TITLE
Create better success and failure Deployment TypeScript types

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#897]
Currently we have a `Deployment`, `PreDeployment`, and `DeploymentError`. However we want to know more about the error states in some of our components. We can make those `isSuccessful` and `isUnsuccessful` functions type predicates informing us that `deploymentError` is not `null`, for example, making them easier to use across the frontend.

**Comment by jonkeane** [comment]
Is this still relevant?

**Comment by dotNomad** [comment]
We can close this one up. The `ContentRecordError` types and predicates have been serving us well, and were cleaned up a bit since this was opened.
